### PR TITLE
curv edits

### PR DESCRIPTION
**Pull request by hardin47**
@matackett (and @mine-cetinkaya-rundel  ??)

Thanks for the great feedback on the first draft.  I think this might be due today-ish for the April issue of Chance??

I added quite a few more words to connect the sections more smoothly.  I also added two more scholars (Desi Small-Rodriquez and Lester Mackey).  

Questions for you:

1. I tried to follow all of the formatting requirements.  I don't know that I did a good job with the references, though.  Do I need to work more on the references (both in text as well as at the end)?

2. I will add an issue template to the CURV repo, but I haven't done that yet.

3. You asked what types of questions I ask after viewing the David Blackwell video.  Tbh, I don't ask questions.  I don't know what to ask.  I find it extremely difficult to generate conversation at that point.  Do you have any suggestions for me?  I would LOVE some help thinking about how to get students to engage with the video... Any ideas?

Thanks again for all your help.  I have a bit of time now, so if you get me feedback, I can turn it around very quickly.  Hope you are having a good semester.

### CODE REVIEW

**Comment by hardin47** [comment]
I added the template for scholar entries on the GitHub website.  Thanks!

**Comment by hardin47** [comment]
I know this is the opposite of what I was supposed to do, but I added one more "further reading" because there is a great JSDSE article on "Teaching the Difficult Past of Statistics to Improve the Future" which totally aligns with the column!

**Comment by matackett** [comment]
Thanks for making the edits. The revised article looks great! We just made some small formatting edits on the citations and URLs and are about to send it to the editors for publication.

**Comment by hardin47** [comment]
woo hoo!!!  Thank you.  i look forward to seeing it in Chance.  :)

**Pull request merged**
